### PR TITLE
support findOneAndUpdate MongoDB command

### PR DESCRIPTION
**Pull request by matthew1534**
@bgschiller another PR sorry! Just adding support for another MongoDB command. I've tested this locally and it works as expected. Cheers! 👍

### CODE REVIEW

**Comment by bgschiller** [comment]
great! would you be up for adding a test that exercises the new function?

**Comment by matthew1534** [comment]
@bgschiller my bad, didn't see the test file otherwise would have popped something in. Test added - let me know if you want anything more specific

**Comment by bgschiller** [comment]
Looks great! It seems like you're making some good improvements to the library. Okay if I add you as a contributor?

**Comment by bgschiller** [comment]
released as version 1.0.8

**Comment by matthew1534** [comment]
@bgschiller would love to be added as a contributor; such a great package - really like it when small packages have a huge impact which this easily does, saves us so much time in development! 👍

**Pull request merged**
